name: js app tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app/

        strategy:
            matrix:
                file_name: [New Text Document.txt]

        env:
            MODE: ${{secrets.MODE}}
        steps:
            - name: github-actions-demo
            - uses: actions/checkout@v2
        
            - name: Run Tests
            run:
                - echo "Running tests for ${{ matrix.file_name }} with config ${{ matrix.other_config }}"
                - echo "Mode: $MODE"  # Access the environment variable
                